set(omt_version "v1.0.0.13")
set(omt_file "OpenMediaTransport.Binaries.Release.${omt_version}.zip")
set(omt_url "https://github.com/openmediatransport/libomtnet/releases/download/${omt_version}/${omt_file}")
set(omt_hash "332829b3ca575e075d08ea6abafcf912e7f09dbaac5d8880199d867d09605e23")
set(omt_libs "${CMAKE_SOURCE_DIR}/lib/omt")

if(NOT EXISTS "${omt_libs}/${omt_file}")
      message(STATUS "Downloading ${omt_url}")
      file(DOWNLOAD "${omt_url}" "${omt_libs}/${omt_file}" STATUS download_status EXPECTED_HASH SHA256=${omt_hash})

      list(GET download_status 0 error_code)
      list(GET download_status 1 error_message)
      if(error_code GREATER 0)
        message(STATUS "Downloading ${omt_url} - Failure")
        message(FATAL_ERROR "Unable to download ${omt_url}, failed with error: ${error_message}")
        file(REMOVE "${omt_libs}/${omt_file}")
      else()
        message(STATUS "Downloading ${omt_url} - done")
        file(ARCHIVE_EXTRACT INPUT "${omt_libs}/${omt_file}" DESTINATION "${omt_libs}")
      endif()
    endif()
