name: Bug Report
description: Report a Bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: input
    id: obs-log
    attributes:
      label: "OBS Log [URL] - Important!"
      description: "In OBS' menu: `Help`->`Log Files`->`Upload Current Log File`. Click `Copy URL` and paste the link here."
      placeholder: "[ex: https://obsproject.com/logs/xp0aoscz...]"
   validations:
      required: false
  - type: input
    id: obs-version
    attributes:
      label: OBS Version
      description: What OBS version(s) does this happen on?
      placeholder: "[ex: 28.0, 29.0.2, 30.2.3]"
    validations:
      required: true
  - type: input
    id: obs-install
    attributes:
      label: OBS Installation Method
      description: How did you install OBS?
      placeholder: "[ex: .exe, .dep, apt, brew, PPA, Flatpak, Snap, winget, ...]"
    validations:
      required: true
  - type: input
    id: distroav-version
    attributes:
      label: DistroAV Version
      description: "The version(s) of DistroAV affected by this bug. OBS menu: `Tools`->`NDI Output Settings`, Title: `DistroAV ...`"
      placeholder: "[ex: 4.14.0]"
    validations:
      required: true
  - type: input
    id: distroav-install
    attributes:
      label: DistroAV Installation Method
      description: How did you install DistroAV?
      placeholder: "[ex: .exe, .dep, apt, brew, PPA, Flatpak, Snap, winget, ...]"
    validations:
      required: true
  - type: input
    id: ndi-version
    attributes:
      label: NDI Version
      description: "What version(s) of NDI does this happen on? OBS menu: `Tools`->`NDI Output Settings`, `NDI SDK ...`"
      placeholder: "[ex: 5.6.0, 6.0.1 ...]"
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: Operation System version(s) impacted?
      placeholder: "[ex: MacOS 15.1, Ubuntu 24.02, Windows 10 22H2, Windows 11 22H2, ...]"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug or reported behavior
      description: Describe the issue or the bug experienced.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: List the steps to reliably reproduce this error?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, paste screenshots here to help explain your problem. Recording & uploading a video might be useful as well.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
